const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAIL = "REGISTER_FAIL";

const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";

export { REGISTER_SUCCESS, REGISTER_FAIL };
export { LOGIN_SUCCESS, LOGIN_FAIL };
